---

- name: Find shell profile scripts
  stat:
    path: "{{ nvm_home }}/{{ item }}"
  with_items: "{{ nvm_shell_profile_scripts }}"
  register: nvm_shell_profile_st

- name: Set NVM_DIR in shell profiles
  lineinfile:
    dest: "{{ nvm_home }}/{{ item.item }}"
    line: 'export NVM_DIR="$HOME/.nvm"'
    regexp: '^export NVM_DIR='
  with_items: "{{ nvm_shell_profile_st.results }}"
  when: item.stat.exists

- name: Source nvm.sh in shell profiles
  lineinfile:
    dest: "{{ nvm_home }}/{{ item.item }}"
    line: '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm'
    insertafter: '^export NVM_DIR='
    regexp: "/nvm.sh"
  with_items: "{{ nvm_shell_profile_st.results }}"
  when: item.stat.exists
